apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #PV NAME
  volumeName: static-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app: static-vol
spec:
  nodeSelector:
    topology.ebs.csi.aws.com/zone: us-east-1b
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim

---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: static-vol
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # target container port
