apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dynamic-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: dynamic-vol
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # target container port
---

apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: dynamic-vol
spec:
  nodeSelector:
    topology.ebs.csi.aws.com/zone: us-east-1b
spec:
  containers:
  - name: nginx
    image: nginx
   
    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-claim