apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-efs-static-lb
spec:
  type: LoadBalancer
  selector:
    app: efs-static-vol
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # target container port

---

apiVersion: v1
kind: Pod
metadata:
  name: efs-app
  labels:
    app: efs-static-vol
spec:
  containers:
  - name: nginx
    image: nginx

    volumeMounts:
    - name: persistent-storage
      mountPath: /usr/share/nginx/html
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim