apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-claim-1
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-dynamic-sc
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-app-1
  labels:
    app: dynamic-efs-prov-vol #label and selector should match
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - name: persistent-storage
          mountPath: /usr/share/nginx/html
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-claim-1

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-dynamic-efs-lb
spec:
  type: LoadBalancer
  selector:
    app: dynamic-efs-prov-vol
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80  # target container port
---