
apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend
  namespace: expense-ns
  labels:
    app: exepnse
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exepnse
      tier: web
  template:
    metadata:
      labels:
        app: exepnse
        tier: web
    spec:
      containers:
      - name: frontend
        image: labhavya/frontend:1.1.0
        ports:
        - containerPort: 8080 #service port

---

#service to make the mysql accessible from backend.

apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: expense-ns
spec:
  type: LoadBalancer
  selector:
    app: exepnse
    tier: web
  ports:
  - name: frontend
    port: 80 #service port, used to acces the website
    targetPort: 8080  # target container port