
apiVersion: v1
kind: Pod
metadata:
  name: expense-pod
  namespace: expense-ns
spec:
  containers:
  - name: nginx
    image: nginx
  - name: almalinux
    image: almalinux:9
    cmd: ["sleep","1000"]