
apiVersion: v1
kind: Pod
metadata:
  name: env-demo
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: course
      value: "Devops with AWS"
    - name: trainer
      value: "siva kumar"
    - name: duration
      value: "120hrs"