
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
labels:
  project: expense
  environment: dev
  component: backup
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    project: expense
    environment: dev
    component: backup
  ports:
  - name: http
    protocal: tcp
    port: 80
    targetport: 9376
  


