

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-LoadBalancer
  labels:
    project: expense
    environment: dev
    component: backup
    type: LoadBalancer-demo
spec:
  containers:
  - name: nginx
    image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-LoadBalancer
spec:
  type: LoadBalancer
  selector:
    project: expense
    environment: dev
    component: backup
    type: LoadBalancer-demo
  ports:
  - protocal: tcp
    port: 80
    targetPort: 80  # target container port
    
  


