
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: exepnse
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
  #replicaset use these labels to find the PODS for creating the desired number of replicas
    matchLabels:
      tier: frontend
      app: exepnse
  #POD template
  template:
    metadata:
      labels:
        tier: frontend
        app: exepnse
    spec:
      containers:
      - name: nginx
        image: nginx
