apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-clu
  region: us-east-1

managedNodeGroups:
  - name: expense-ng
    instanceTypes: ["m5.large","c4.large","c5.large","c5d.large","c5n.large","c5a.large"]
    desiredCapacity: 3
    spot: true

