apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: expense-ns
  labels:
    app: exepnse
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exepnse
      tier: web
  template:
    metadata:
      labels:
        app: exepnse
        tier: web
    spec:
      containers:
      - name: frontend
        image: labhavya/frontend:1.3.0    # got this from DockerRepo/fronend
        resources:
    #soft limits
          requests: 
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "100Mi"
            cpu: "150m"

        ports:
        - containerPort: 8080 #service port

---

#scaling policy
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scaling-pol1
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 5

---
#service to make the mysql accessible from backend.

apiVersion: v1
kind: Service

metadata:
  name: frontend
  namespace: expense-ns
spec:
  type: LoadBalancer
  selector:
    app: exepnse
    tier: web
  ports:
  - name: frontend
    port: 80 #service port, used to acces the website
    targetPort: 8080  # target container port