apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-mysql
data:
  DB_HOST: mysql
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense-ns
  labels:
    app: expense
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense
      tier: backend
  template:
    metadata:
      labels:
        app: expense
        tier: backend
    spec:
      containers:
      - name: backend
        image: labhavya/backend:1.1.0
        envFrom:
        - configMapRef:
            name: configmap-mysql       
        ports:
        - containerPort: 8080 #service port



---
#service to make the mysql accessible from backend.

apiVersion: v1
kind: Service

metadata:
  name: backend
  namespace: expense-ns
spec:
  selector:
    app: expense
    tier: backend
  ports:
  - name: backend
    port: 8080 #service port
    targetPort: 8080  # target container port